
image: python:3.8-slim

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/


before_script:
  - apt-get update && apt-get --assume-yes install netcat
  - sed settings.ini.template > settings.ini.
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
 
test:
  services:
    - selenium/standalone-chrome
  script:
    - nohup python3 -m flask run &
    - sleep 5
    - python3 -m behave features