
image: docker/compose:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip
    - venv/


before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
 
test:
  services:
    - selenium/standalone-chrome

  script:
    - docker-compose up &
    - sleep 10
    - python -m behave features
