
image: ubuntu:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip
    - venv/

before_script:
    - apt-get update && apt-get --assume-yes install docker && apt-get install python3
    - sed settings.ini.template > settings.ini.
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"


docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - docker build --pull -t "saed123/connect-four:latest" .
    - docker push "saed123/connect-four:latest"
  # Run this job in a branch where a Dockerfile exists
 
test:

  services:
    - selenium/standalone-chrome
    - saed123/connect-four
    - docker:dind
  
  script:
    - python3 -m behave features