
image: "python:3.8.9"

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version  # For debugging
  - pip install -r requirements.txt
  - virtualenv venv
  - source venv/bin/activate

run:
  script:
    - python3 user-interface/GameBoard.py --arg myArg < inputs.txt
    - gameBoard = GameBoard()
    - gameBoard.startGame()
  artifacts:
    when: always