
image: "python:3.8.9"

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - sed settings.ini.template > settings.ini.
  - python --version  # For debugging
  - pip install -r requirements.txt
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - Xvfb :1 & export DISPLAY=:1

run:
  script:
    - SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dis
    - python3 user-interface/RunGame.py --arg myArg < inputs.txt
  artifacts:
    when: always