
image: python:3.8-slim

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/


before_script:
  - apt-get update && apt-get --assume-yes install netcat && apt-get install docker-compose
  - sed settings.ini.template > settings.ini.
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

run:
  script:
    - systemctl start python3 app.py
  artifacts:
    when: always