
image: python:3.8-slim

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip
    - venv/


docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.mygit.th-deg.de
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch _name (commit ref slug)
  script:
    - docker build . -t ${CI_REGISTRY_IMAGE}/connect-four:${CI_COMMIT_REF_SLUG}
    - docker push ${CI_REGISTRY_IMAGE}/connect-four:${CI_COMMIT_REF_SLUG}
  # Run this job in a branch where a Dockerfile exists
  after_script:
    - docker rmi ${CI_REGISTRY_IMAGE}/connect-four:${CI_COMMIT_REF_SLUG}


test:
  image: docker:latest
  variables:
    GCD_CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}/connect-four:${CI_COMMIT_REF_SLUG}
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.mygit.th-deg.de

  services:
    - selenium/standalone-chrome
  script:
    - apk add --update python3.9.8-slim
    - python3 -m ensurepip
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - python3 -m pip install --upgrade pip
    - pip3 install -r requirements.txt
    - python3 -m behave features
  after_script:
    - docker rmi ${CI_REGISTRY_IMAGE}/connect-four:${CI_COMMIT_REF_SLUG}

