version: '2'
services:
    connect-four:
      container_name: connect-four
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
        target: prod
      image: base_prod
      ports:
        - 5000:5000
