version: '2'
services:
    connect-four:
      container_name: connect-four
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
        target: dev
      image: base_dev
      ports:
        - 3000:5000
    cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '6379:6379'
      command: --save 20 1 --loglevel warning
      volumes:
        - cache:/data
volumes:
  cache:
    driver: local