version: '2'
services:
    connect-four:
      container_name: connect-four
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
        target: prod
      image: base_prod
      ports:
        - 3000:5000
      depends_on:
        - chrome-container

    chrome-container:
      container_name: chrome-container
      image: selenium/standalone-chrome
      volumes:
        - /dev/shm:/dev/shm
      ports:
        - "4444:4444"