version: '2'
services:
    connect-four:
      container_name: connect-four
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
        target: dev
      image: base_dev
      ports:
        - 3000:5000