version: '2'
services:
    connect-four:
      container_name: connect_four
      stdin_open: true
      tty: true
      environment:
        - REDIS_HOST=redis
      build:
        context: .
        dockerfile: Dockerfile
      image: base_dev
      ports:
        - 3000:5000
    redis:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '6379:6379'
      command: --save 20 1 --loglevel warning
      volumes:
        - redis:/data
volumes:
  redis:
    driver: local